#!/usr/bin/env node

const server = require('./server')
const client = require('./client')

const program = require('commander')

const log = `
_     _   _                                         
| |   | | | |                                        
| |__ | |_| |_ _ __ ______ _ __  _ __ _____  ___   _ 
| '_ \| __| __| '_ \______| '_ \| '__/ _ \ \/ / | | |
| | | | |_| |_| |_) |     | |_) | | | (_) >  <| |_| |
|_| |_|\__|\__| .__/      | .__/|_|  \___/_/\_\\__, |
              | |         | |                   __/ |
              |_|         |_|                  |___/ 
`



console.log("\x1b[32m", log)
console.log("\x1b[0m")

program
  .version('1.0.0')

program.command('server')
       .description('在指定端口开启服务端监听')
       .option('-p, --port <port>', '指定的端口')
       .action((port) => {
          server(~~port)
       })

program.command('client')
       .description('连接指定的服务端, 并将请求转发至本地指定端口')
       .option('-s, --server <server>', '指定的服务端IP')
       .option('-p, --port <port>', '指定的端口')
       .action(({server, port}) => {
          client(server, ~~port)
       })


program.parse(process.argv)
